# Multivariate Liner Regression(traditional method)

In [19]:
import torch

In [20]:
# data set생성
x_train = torch.FloatTensor([[73, 80, 75],[93, 88, 93],[89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [31]:
w = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [32]:
optimizer = torch.optim.SGD([w, b], lr = 0.00001)
nb_epoch = 1000

In [37]:
for epoch in range(nb_epoch + 1):
    hypothesis = torch.matmul(x_train, w) + b
    cost = torch.mean((hypothesis - y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print("epoch : ", epoch, end = "")
        print("cost : ", cost)        

epoch :  0cost :  tensor(3.9386, grad_fn=<MeanBackward0>)
epoch :  100cost :  tensor(3.7808, grad_fn=<MeanBackward0>)
epoch :  200cost :  tensor(3.6301, grad_fn=<MeanBackward0>)
epoch :  300cost :  tensor(3.4861, grad_fn=<MeanBackward0>)
epoch :  400cost :  tensor(3.3486, grad_fn=<MeanBackward0>)
epoch :  500cost :  tensor(3.2172, grad_fn=<MeanBackward0>)
epoch :  600cost :  tensor(3.0915, grad_fn=<MeanBackward0>)
epoch :  700cost :  tensor(2.9714, grad_fn=<MeanBackward0>)
epoch :  800cost :  tensor(2.8564, grad_fn=<MeanBackward0>)
epoch :  900cost :  tensor(2.7465, grad_fn=<MeanBackward0>)
epoch :  1000cost :  tensor(2.6413, grad_fn=<MeanBackward0>)


In [38]:
print(hypothesis)

tensor([[153.7200],
        [184.7362],
        [177.3524],
        [197.6775],
        [141.4046]], grad_fn=<AddBackward0>)




# Multivariate Linear Regression(using nn.Module)

In [61]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [63]:
x_train = torch.FloatTensor([[73, 80, 75],[93, 88, 93],[89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [66]:
model = nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [71]:
nb_epochs = 10000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 1000 == 0:
        print("epoch : ", epoch, "cost : ", cost)

epoch :  0 cost :  tensor(0.2292, grad_fn=<MseLossBackward>)
epoch :  1000 cost :  tensor(0.1963, grad_fn=<MseLossBackward>)
epoch :  2000 cost :  tensor(0.1736, grad_fn=<MseLossBackward>)
epoch :  3000 cost :  tensor(0.1579, grad_fn=<MseLossBackward>)
epoch :  4000 cost :  tensor(0.1471, grad_fn=<MseLossBackward>)
epoch :  5000 cost :  tensor(0.1396, grad_fn=<MseLossBackward>)
epoch :  6000 cost :  tensor(0.1344, grad_fn=<MseLossBackward>)
epoch :  7000 cost :  tensor(0.1308, grad_fn=<MseLossBackward>)
epoch :  8000 cost :  tensor(0.1283, grad_fn=<MseLossBackward>)
epoch :  9000 cost :  tensor(0.1265, grad_fn=<MseLossBackward>)
epoch :  10000 cost :  tensor(0.1253, grad_fn=<MseLossBackward>)


In [74]:
print(prediction)

tensor([[152.4316],
        [184.6210],
        [179.7697],
        [195.8817],
        [142.4790]], grad_fn=<AddmmBackward>)


In [75]:
print(y_train)

tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


# Multivariate Linear Regression(using Class)

In [76]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [77]:
class MultivariateLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    
    def forward(self, x):
        return self.linear(x)

In [78]:
x_train = torch.FloatTensor([[73, 80, 75],[93, 88, 93],[89, 91, 80], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [84]:
model = MultivariateLinearRegression()
nb_epoches = 10000
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [85]:
for epoch in range(nb_epoches + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 1000 == 0: 
        print("epoch : ", epoch, "cost : ", cost)

epoch :  0 cost :  tensor(67629.8281, grad_fn=<MseLossBackward>)
epoch :  1000 cost :  tensor(5.9577, grad_fn=<MseLossBackward>)
epoch :  2000 cost :  tensor(4.0263, grad_fn=<MseLossBackward>)
epoch :  3000 cost :  tensor(2.7619, grad_fn=<MseLossBackward>)
epoch :  4000 cost :  tensor(1.9210, grad_fn=<MseLossBackward>)
epoch :  5000 cost :  tensor(1.3554, grad_fn=<MseLossBackward>)
epoch :  6000 cost :  tensor(0.9717, grad_fn=<MseLossBackward>)
epoch :  7000 cost :  tensor(0.7099, grad_fn=<MseLossBackward>)
epoch :  8000 cost :  tensor(0.5305, grad_fn=<MseLossBackward>)
epoch :  9000 cost :  tensor(0.4073, grad_fn=<MseLossBackward>)
epoch :  10000 cost :  tensor(0.3225, grad_fn=<MseLossBackward>)


In [86]:
print(prediction)

tensor([[152.9227],
        [184.4800],
        [179.3608],
        [196.2732],
        [142.0862]], grad_fn=<AddmmBackward>)
