# 1. 훈련 데이터 전처리하기

### <font color='purple'> apple를 입력받으면 pple!를 출력하는 RNN </font> 

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np

In [5]:
input_str = "apple"
label_str = "pple!"
char_vocab = sorted(list(set(input_str + label_str)))
vocab_size = len(char_vocab)
print("문자 집합의 크기 :", vocab_size)

문자 집합의 크기 : 5


In [6]:
input_size = vocab_size
hidden_size = 5
output_size = 5
learning_rate = 0.1

In [10]:
# 문자 집합에 교유 정수 부여합니다
char_to_index = {word : i for i, word in enumerate(char_vocab)}
print(char_to_index)

{'!': 0, 'a': 1, 'e': 2, 'l': 3, 'p': 4}


In [21]:
x_data = [char_to_index[c] for c in input_str]
y_data = [char_to_index[c] for c in label_str]
print(x_data)
print(y_data)

[1, 4, 4, 3, 2]
[4, 4, 3, 2, 0]


In [22]:
x_data = torch.unsqueeze(torch.LongTensor(x_data), 0)
y_data = torch.unsqueeze(torch.LongTensor(y_data), 0)
print(x_data)
print(y_data)

tensor([[1, 4, 4, 3, 2]])
tensor([[4, 4, 3, 2, 0]])


In [33]:
x_one_hot = [np.eye(vocab_size)[x] for x in x_data]
x_one_hot = torch.FloatTensor(x_one_hot)

In [34]:
print(x_one_hot)

tensor([[[0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0.]]])
